Added new partner
freud/GreenfieldConf pull request #8
Opened 2020-03-10 11:22 UTC by krzysiek-b

Zmiany dla logo do przeglądu. Niestety logo ma zupełnie inną proporcję niż te wcześniejsze przez co wyglda nie za dobrze.

Tak to wygląda obecnie.
![image](https://user-images.githubusercontent.com/6192236/76307809-cf0e7080-62c9-11ea-8564-586ee2f9777d.png)

2020-03-10 13:07 UTC, magdzikk requested changes

2020-03-10 13:07 UTC, magdzikk commented on _includes/partners.html
> +                title="kielce-jug-index"
Atrybut "title" powinien mieć wartość "Kielce JUG".
Btw przy okazji Radio Index ma "radio-index", a powinno mieć "Radio Index" albo "Akademickie Radio Index
Uniwersytetu Zielonogórskiego", a KGD.NET ma "KDG .NET" zamiast "KGD .NET" (literówka)

2020-03-10 13:20 UTC, krzysiek-b commented on _includes/partners.html
> +                title="kielce-jug-index"
Dziękuje, poprawiłem. Troche za szybko zasugerowałem się tym co było :)

2020-03-10 14:45 UTC, magdzikk commented on _includes/partners.html
> +                title="kielce-jug-index"
super :)

2020-03-10 14:45 UTC, magdzikk approved these changes

2020-03-13 08:18 UTC, orchowski approved these changes

2020-03-13 08:40 UTC, orchowski commented
Zepsułem i nie mam jak naprawić przed 16

2020-03-13 08:51 UTC, merged